"""
Retail & Marketing Analytics - Live Dashboard
Streamlit app tying together the outputs of Notebooks 01-06.

Run from the project root with:
    streamlit run app.py

Expects the following to already exist (generated by the notebooks):
    data/processed/cleaned_retail_sales.csv
    data/processed/monthly_kpis.csv
    data/processed/customer_segments.csv
    data/processed/customer_clv.csv
    data/processed/churn_features.csv
    data/processed/churn_predictions.csv
    outputs/reports/kpi_summary.csv
    outputs/reports/category_kpis.csv
    outputs/reports/regional_kpis.csv
    outputs/models/churn_model_rf.pkl
    outputs/models/churn_scaler.pkl
    outputs/models/churn_feature_columns.pkl
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import joblib
from pathlib import Path

st.set_page_config(
    page_title="Retail & Marketing Analytics",
    page_icon=None,
    layout="wide"
)

DATA_PROCESSED = Path("data/processed")
OUTPUTS_REPORTS = Path("outputs/reports")
OUTPUTS_MODELS = Path("outputs/models")


# ---------------------------------------------------------------------------
# Data loading (cached so the app stays fast on repeated interactions)
# ---------------------------------------------------------------------------

@st.cache_data
def load_csv(path):
    if path.exists():
        return pd.read_csv(path)
    return None


@st.cache_resource
def load_churn_model():
    # Notebook 06 saves the best of Logistic Regression / tuned Random Forest / XGBoost
    # as churn_model_best.pkl. Falls back to the older churn_model_rf.pkl name for
    # compatibility with projects still on the earlier version of Notebook 06.
    model_path = OUTPUTS_MODELS / "churn_model_best.pkl"
    if not model_path.exists():
        model_path = OUTPUTS_MODELS / "churn_model_rf.pkl"
    scaler_path = OUTPUTS_MODELS / "churn_scaler.pkl"
    cols_path = OUTPUTS_MODELS / "churn_feature_columns.pkl"
    if model_path.exists() and scaler_path.exists() and cols_path.exists():
        model = joblib.load(model_path)
        scaler = joblib.load(scaler_path)
        feature_cols = joblib.load(cols_path)
        return model, scaler, feature_cols
    return None, None, None


kpi_df = load_csv(OUTPUTS_REPORTS / "kpi_summary.csv")
monthly_kpis = load_csv(DATA_PROCESSED / "monthly_kpis.csv")
category_kpis = load_csv(OUTPUTS_REPORTS / "category_kpis.csv")
regional_kpis = load_csv(OUTPUTS_REPORTS / "regional_kpis.csv")
rfm = load_csv(DATA_PROCESSED / "customer_segments.csv")
churn_features = load_csv(DATA_PROCESSED / "churn_features.csv")
churn_predictions = load_csv(DATA_PROCESSED / "churn_predictions.csv")

model, scaler, feature_cols = load_churn_model()


def kpi_value(name, default=0.0):
    if kpi_df is None:
        return default
    match = kpi_df[kpi_df["KPI"] == name]
    if match.empty:
        return default
    try:
        return float(match["Value"].values[0])
    except (ValueError, TypeError):
        return default


# ---------------------------------------------------------------------------
# Sidebar navigation
# ---------------------------------------------------------------------------

st.sidebar.title("Retail & Marketing Analytics")
st.sidebar.caption("Customer Segmentation & Sales Optimization")
page = st.sidebar.radio(
    "Navigate",
    ["Overview", "Customer Segments", "Churn Risk Lookup", "Revenue at Risk"]
)
st.sidebar.markdown("---")
st.sidebar.caption(
    "Data source: Notebooks 01-06\n\n"
    "Segmentation: RFM + K-Means clustering\n\n"
    "Prediction: Random Forest churn model"
)


# ---------------------------------------------------------------------------
# Page 1: Overview
# ---------------------------------------------------------------------------

if page == "Overview":
    st.title("Executive Overview")

    if kpi_df is None:
        st.warning(
            "outputs/reports/kpi_summary.csv not found. "
            "Run Notebook 05 (KPI Design and Dashboard Preparation) first."
        )
    else:
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Revenue", f"${kpi_value('Total_Revenue'):,.0f}")
        col2.metric("Total Customers", f"{kpi_value('Total_Customers'):,.0f}")
        col3.metric("Avg Order Value", f"${kpi_value('Avg_Order_Value'):,.2f}")
        col4.metric("Retention Rate", f"{kpi_value('Retention_Rate'):.1f}%")

        col5, col6, col7, col8 = st.columns(4)
        col5.metric("Total Orders", f"{kpi_value('Total_Orders'):,.0f}")
        col6.metric("Repeat Customer Rate", f"{kpi_value('Repeat_Customer_Rate'):.1f}%")
        col7.metric("CLV / CAC Ratio", f"{kpi_value('CLV_to_CAC_Ratio'):.2f}x")
        col8.metric("Churn Rate", f"{kpi_value('Churn_Rate'):.1f}%")

        st.markdown("---")

        if monthly_kpis is not None and "YearMonth" in monthly_kpis.columns:
            st.subheader("Monthly Revenue Trend")
            fig = px.line(
                monthly_kpis, x="YearMonth", y="Revenue", markers=True,
                labels={"Revenue": "Revenue ($)", "YearMonth": "Month"}
            )
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)

        col_a, col_b = st.columns(2)

        with col_a:
            if category_kpis is not None and "Product_Category" in category_kpis.columns:
                st.subheader("Revenue by Category")
                fig = px.pie(
                    category_kpis, values="Total_Revenue", names="Product_Category",
                    hole=0.45
                )
                fig.update_layout(height=380)
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("Category KPIs not available for this dataset.")

        with col_b:
            if regional_kpis is not None and "Region" in regional_kpis.columns:
                st.subheader("Revenue by Region")
                fig = px.bar(
                    regional_kpis.sort_values("Total_Revenue", ascending=False),
                    x="Region", y="Total_Revenue", color="Region",
                    labels={"Total_Revenue": "Revenue ($)"}
                )
                fig.update_layout(height=380, showlegend=False)
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("Regional KPIs not available for this dataset.")


# ---------------------------------------------------------------------------
# Page 2: Customer Segments
# ---------------------------------------------------------------------------

elif page == "Customer Segments":
    st.title("Customer Segmentation (RFM + Clustering)")

    if rfm is None:
        st.warning(
            "data/processed/customer_segments.csv not found. "
            "Run Notebook 04 (Customer Segmentation and Advanced Analytics) first."
        )
    else:
        segment_col = "Cluster_Name" if "Cluster_Name" in rfm.columns else "Customer_Segment"
        all_segments = sorted(rfm[segment_col].dropna().unique().tolist())
        selected_segments = st.multiselect(
            "Filter by segment", all_segments, default=all_segments
        )
        filtered = rfm[rfm[segment_col].isin(selected_segments)]

        col1, col2, col3 = st.columns(3)
        col1.metric("Customers in View", f"{len(filtered):,}")
        col2.metric("Avg Recency (days)", f"{filtered['Recency'].mean():.1f}")
        col3.metric("Avg Monetary Value", f"${filtered['Monetary'].mean():,.2f}")

        col_a, col_b = st.columns(2)
        with col_a:
            st.subheader("Segment Sizes")
            counts = filtered[segment_col].value_counts().reset_index()
            counts.columns = [segment_col, "Count"]
            fig = px.bar(counts, x=segment_col, y="Count", color=segment_col)
            fig.update_layout(height=380, showlegend=False)
            st.plotly_chart(fig, use_container_width=True)

        with col_b:
            st.subheader("Revenue Share by Segment")
            revenue_by_segment = filtered.groupby(segment_col)["Monetary"].sum().reset_index()
            fig = px.pie(revenue_by_segment, names=segment_col, values="Monetary", hole=0.45)
            fig.update_layout(height=380)
            st.plotly_chart(fig, use_container_width=True)

        st.subheader("RFM Space (3D)")
        fig = px.scatter_3d(
            filtered, x="Recency", y="Frequency", z="Monetary", color=segment_col,
            hover_data=["Customer_ID"], opacity=0.7
        )
        fig.update_layout(height=550)
        st.plotly_chart(fig, use_container_width=True)

        st.subheader("Segment Summary Table")
        summary = filtered.groupby(segment_col).agg(
            Customers=("Customer_ID", "count"),
            Avg_Recency=("Recency", "mean"),
            Avg_Frequency=("Frequency", "mean"),
            Avg_Monetary=("Monetary", "mean"),
            Total_Revenue=("Monetary", "sum"),
        ).round(2).sort_values("Total_Revenue", ascending=False)
        st.dataframe(summary, use_container_width=True)


# ---------------------------------------------------------------------------
# Page 3: Churn Risk Lookup
# ---------------------------------------------------------------------------

elif page == "Churn Risk Lookup":
    st.title("Customer Churn Risk Lookup")

    if model is None or scaler is None or feature_cols is None:
        st.warning(
            "Churn model artifacts not found in outputs/models/. "
            "Run Notebook 06 (Customer Churn Prediction) first."
        )
    elif churn_features is None:
        st.warning(
            "data/processed/churn_features.csv not found. "
            "Run Notebook 06 (Customer Churn Prediction) first."
        )
    else:
        categorical_features = [
            c for c in ["Preferred_Category", "Preferred_Region", "Customer_Type", "CLV_Category"]
            if c in churn_features.columns
        ]

        customer_ids = churn_features["Customer_ID"].astype(str).tolist()
        selected_id = st.selectbox("Select a Customer ID", customer_ids)

        row = churn_features[churn_features["Customer_ID"].astype(str) == selected_id]

        if not row.empty:
            X_row = row.drop(columns=["Customer_ID", "Churned"], errors="ignore")
            X_encoded = pd.get_dummies(X_row, columns=categorical_features, drop_first=True)
            X_aligned = X_encoded.reindex(columns=feature_cols, fill_value=0)
            X_scaled = scaler.transform(X_aligned)
            churn_probability = float(model.predict_proba(X_scaled)[0][1])

            if churn_probability >= 0.66:
                risk_tier = "High"
            elif churn_probability >= 0.33:
                risk_tier = "Medium"
            else:
                risk_tier = "Low"

            col1, col2, col3 = st.columns(3)
            col1.metric("Churn Probability", f"{churn_probability * 100:.1f}%")
            col2.metric("Risk Tier", risk_tier)
            if "Total_Sales" in row.columns:
                col3.metric("Historical Revenue", f"${row['Total_Sales'].values[0]:,.2f}")

            st.progress(min(int(churn_probability * 100), 100))

            st.subheader("Customer Profile")
            profile = row.drop(columns=["Customer_ID"], errors="ignore").T
            profile.columns = ["Value"]
            st.dataframe(profile, use_container_width=True)

        st.markdown("---")
        st.subheader("Top 20 Highest-Risk Customers")
        if churn_predictions is not None:
            display_cols = [c for c in ["Customer_ID", "Churn_Probability", "Total_Sales", "CLV_Simple"]
                             if c in churn_predictions.columns]
            top_risk = churn_predictions.sort_values("Churn_Probability", ascending=False).head(20)
            st.dataframe(top_risk[display_cols], use_container_width=True)


# ---------------------------------------------------------------------------
# Page 4: Revenue at Risk
# ---------------------------------------------------------------------------

elif page == "Revenue at Risk":
    st.title("Revenue at Risk")

    if churn_predictions is None:
        st.warning(
            "data/processed/churn_predictions.csv not found. "
            "Run Notebook 06 (Customer Churn Prediction) first."
        )
    else:
        top_pct = st.slider(
            "High-risk threshold: top % of customers by churn probability",
            min_value=5, max_value=50, value=20, step=5
        )
        cutoff = churn_predictions["Churn_Probability"].quantile(1 - top_pct / 100)
        high_risk = churn_predictions[churn_predictions["Churn_Probability"] >= cutoff]

        total_revenue = churn_predictions["Total_Sales"].sum() if "Total_Sales" in churn_predictions.columns else 0
        at_risk_revenue = high_risk["Total_Sales"].sum() if "Total_Sales" in high_risk.columns else 0
        pct_of_total = (at_risk_revenue / total_revenue * 100) if total_revenue else 0

        col1, col2, col3 = st.columns(3)
        col1.metric("High-Risk Customers", f"{len(high_risk):,}")
        col2.metric("Revenue at Risk", f"${at_risk_revenue:,.2f}")
        col3.metric("Share of Total Revenue", f"{pct_of_total:.1f}%")

        st.subheader("Churn Probability Distribution")
        fig = px.histogram(
            churn_predictions, x="Churn_Probability", nbins=30,
            labels={"Churn_Probability": "Predicted Churn Probability"}
        )
        fig.add_vline(x=cutoff, line_dash="dash", line_color="red",
                       annotation_text=f"Top {top_pct}% cutoff")
        fig.update_layout(height=380)
        st.plotly_chart(fig, use_container_width=True)

        st.subheader(f"High-Risk Customer List (Top {top_pct}%)")
        display_cols = [c for c in ["Customer_ID", "Churn_Probability", "Total_Sales", "CLV_Simple", "Actual_Churn"]
                         if c in high_risk.columns]
        st.dataframe(
            high_risk.sort_values("Churn_Probability", ascending=False)[display_cols],
            use_container_width=True
        )

        csv_bytes = high_risk[display_cols].to_csv(index=False).encode("utf-8")
        st.download_button(
            "Download High-Risk Customer List (CSV)",
            data=csv_bytes,
            file_name="high_risk_customers.csv",
            mime="text/csv"
        )
